# Generated by Django 4.2.13 on 2025-05-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeteoStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_nbr", models.IntegerField()),
                ("city", models.CharField(max_length=250)),
                ("state", models.CharField(max_length=250)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "verbose_name": "Метеостанция",
                "verbose_name_plural": "Метеостанции",
                "db_table": "stations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PredictionReal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предсказание по погоде",
                "verbose_name_plural": "Предсказания по погоде",
                "db_table": "prediction_real_weather",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PredictionWithout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Беспогодное предсказание",
                "verbose_name_plural": "Беспогодные предсказания",
                "db_table": "prediction_base_weather",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_nbr", models.IntegerField()),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
                "db_table": "stores",
                "managed": False,
            },
        ),
    ]
