# Generated by Django 4.2.13 on 2025-05-27 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("week", "Неделя"),
                            ("month", "Месяц"),
                            ("season", "Сезон"),
                            ("period", "Период"),
                        ],
                        max_length=10,
                        verbose_name="Период",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Начало периода")),
                ("period_end", models.DateField(verbose_name="Конец периода")),
                (
                    "store_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Код магазина",
                    ),
                ),
                (
                    "store_item_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Код товара"
                    ),
                ),
                ("is_rain", models.BooleanField(default=False, verbose_name="Дождь")),
                ("is_snow", models.BooleanField(default=False, verbose_name="Снег")),
                (
                    "avg_temp",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(-50),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Средняя температура",
                    ),
                ),
                (
                    "precip_amount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="Количество осадков (мм)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Исследование",
                "verbose_name_plural": "Исследования",
                "ordering": ["-created_at"],
            },
        ),
    ]
