# Generated by Django 4.2.13 on 2025-05-27 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_research"),
    ]

    operations = [
        migrations.AlterField(
            model_name="research",
            name="precip_amount",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ],
                verbose_name="Количество осадков (мм)",
            ),
        ),
    ]
