# Generated by Django 4.2.13 on 2025-05-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_research_precip_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionResearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_date", models.DateField()),
                ("store_code", models.CharField(max_length=250)),
                ("store_item_code", models.CharField(max_length=250)),
                ("units_yesterday", models.FloatField()),
                ("units_prev_week", models.FloatField()),
                ("tmax", models.FloatField()),
                ("tmin", models.FloatField()),
                ("tavg", models.FloatField()),
                ("depart", models.FloatField()),
                ("dewpoint", models.FloatField()),
                ("wetbulb", models.FloatField()),
                ("heat", models.FloatField()),
                ("cool", models.FloatField()),
                ("sunrise", models.FloatField()),
                ("sunset", models.FloatField()),
                ("snowfall", models.FloatField()),
                ("preciptotal", models.FloatField()),
                ("stnpressure", models.FloatField()),
                ("sealevel", models.FloatField()),
                ("resultspeed", models.FloatField()),
                ("resultdir", models.FloatField()),
                ("avgspeed", models.FloatField()),
                ("year", models.FloatField()),
                ("week", models.FloatField()),
                ("BCFG", models.FloatField()),
                ("BLDU", models.FloatField()),
                ("BLSN", models.FloatField()),
                ("BR", models.FloatField()),
                ("DU", models.FloatField()),
                ("DZ", models.FloatField()),
                ("FG", models.FloatField()),
                ("FU", models.FloatField()),
                ("FZDZ", models.FloatField()),
                ("FZFG", models.FloatField()),
                ("FZRA", models.FloatField()),
                ("GR", models.FloatField()),
                ("GS", models.FloatField()),
                ("HZ", models.FloatField()),
                ("MIFG", models.FloatField()),
                ("PL", models.FloatField()),
                ("PRFG", models.FloatField()),
                ("RA", models.FloatField()),
                ("SG", models.FloatField()),
                ("SN", models.FloatField()),
                ("SQ", models.FloatField()),
                ("TS", models.FloatField()),
                ("TSRA", models.FloatField()),
                ("TSSN", models.FloatField()),
                ("UP", models.FloatField()),
                ("VCFG", models.FloatField()),
                ("VCTS", models.FloatField()),
                ("day_of_week", models.FloatField()),
                ("month", models.FloatField()),
                ("is_weekend", models.FloatField()),
                ("is_holiday", models.FloatField()),
                ("rain_streak", models.FloatField()),
                ("dry_streak", models.FloatField()),
                ("avg_temp_next_day", models.FloatField()),
                ("rain_next_day", models.FloatField()),
                ("days_to_holiday", models.FloatField()),
                ("units", models.FloatField()),
                ("units_pred", models.FloatField()),
                ("shap", models.JSONField()),
                (
                    "difference",
                    models.FloatField(
                        default=0, verbose_name="Разница с реальным предсказанием"
                    ),
                ),
                (
                    "coefficient",
                    models.FloatField(
                        default=1, verbose_name="Отношение к реальному предсказанию"
                    ),
                ),
                (
                    "real",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.predictionreal",
                    ),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.research"
                    ),
                ),
            ],
            options={
                "verbose_name": "Предсказание для исследования",
                "verbose_name_plural": "Предсказания для исследований",
            },
        ),
    ]
