# Generated by Django 4.2.13 on 2025-05-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_predictionresearch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictionresearch",
            name="shap",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="predictionresearch",
            name="units",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="predictionresearch",
            name="units_pred",
            field=models.FloatField(null=True),
        ),
    ]
