# Generated by Django 4.2.13 on 2025-05-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_predictionresearch_shap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="research",
            name="avg_ratio",
            field=models.FloatField(null=True, verbose_name="Средний коэффициент"),
        ),
        migrations.AddField(
            model_name="research",
            name="items_ratios_json",
            field=models.JSONField(null=True, verbose_name="Коэффициенты для итемнов"),
        ),
        migrations.AddField(
            model_name="research",
            name="units_change",
            field=models.FloatField(null=True, verbose_name="Проданно при иной погоде"),
        ),
        migrations.AddField(
            model_name="research",
            name="units_over",
            field=models.FloatField(null=True, verbose_name="Превышение спроса"),
        ),
        migrations.AddField(
            model_name="research",
            name="units_real",
            field=models.FloatField(null=True, verbose_name="Реально продано"),
        ),
    ]
